default_region            = "us-east-1"
docker_username           = "matlau"
github_username           = "MatthewCYLau"
github_project_name       = "node-aws-fargate-terraform"
app_name                  = "node-aws-fargate-app"
environment               = "staging"
mongo_password_secret_arn = "arn:aws:secretsmanager:us-east-1:830663695860:secret:MongoPassword-6hBjo2"